version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../database/migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: node
      POSTGRES_USER: node
      POSTGRES_DB: node

volumes:
  postgres-data: