name: Test math

on:
  push:
    branches: ["master"]
    paths:
      - .github/workflows/test-clojure.yml
      - math/**
  pull_request:
    branches: ["master"]
    paths:
      - .github/workflows/test-clojure.yml
      - math/**

jobs:
  test-clj:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Prepare java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt
          java-version: 16.0.2

      - name: Install Clojure tooling
        uses: DeLaGuardo/setup-clojure@3.7
        with:
          cli: 1.10.1.693

      - name: Run Clojure tests
        working-directory: math
        # Runs all except integration tests which require database and setup/teardown
        run: "clojure -M:test"
